client.on("voiceStateUpdate", async (reaweneski, reawenyeni) => {
let qwe = client.channels.cache.get("log kanal id");
if (!reaweneski.channelID && reawenyeni.channelID) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` isimli ses kanalina katildi!`).catch();
if (reaweneski.channelID && !reawenyeni.channelID) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reaweneski.channelID).name}\` adli ses kanalindan ayrildi`).catch();
if (reaweneski.channelID && reawenyeni.channelID && reaweneski.channelID != reawenyeni.channelID) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` adli kullanici \`${reawenyeni.guild.channels.cache.get(reaweneski.channelID).name}\` adli ses kanailndan cikip \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli ses kanalina girdi`).catch();
if (reaweneski.channelID && reaweneski.selfMute && !reawenyeni.selfMute) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanalda kendi susturmasini kaldirdi`).catch();
if (reaweneski.channelID && !reaweneski.selfMute && reawenyeni.selfMute) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanalda knedisiini susturdu`).catch();
if (reaweneski.channelID && reaweneski.selfDeaf && !reawenyeni.selfDeaf) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanalda kulakligini acti`).catch();
if (reaweneski.channelID && !reaweneski.selfDeaf && reawenyeni.selfDeaf) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanalda kulakligini kapapdi`).catch();
if (reaweneski.channelID && !reaweneski.serverMute && reawenyeni.serverMute) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanaldayken suncuuda mute yedi`).catch();
if (reaweneski.channelID && reaweneski.serverMute && !reawenyeni.serverMute) return qwe.send(`\`${reawenyeni.guild.members.cache.get(reawenyeni.id).displayName}\` salagi \`${reawenyeni.guild.channels.cache.get(reawenyeni.channelID).name}\` adli kanaldayken sunucudaki mutesi acildi`).catch();
})
